import { useEffect, useMemo, useRef, useState, type Dispatch, type SetStateAction, type CSSProperties, type ReactNode } from 'react'
import './styles.css'
import { id, nums, rnd, shuffle, fmt, type GameId, type Player, type Round } from './keno'
import { supabase, supabaseConfigured } from './lib/supabase'

type Profile = Player & { role: 'player' | 'admin' }
type LocalStore = { players: Player[]; rounds: Round[]; session: string | null; admin: boolean }
const LOCAL_KEY = 'kenoplay-demo-v5'
const ADMIN_EMAIL = 'admin@kenodemo.local'
const ADMIN_PASSWORD = 'Admin123!'
const games: {id:GameId;label:string;icon:string}[] = [{id:'keno',label:'Keno',icon:'80'},{id:'aviator',label:'Aviator',icon:'✈'},{id:'dice',label:'Dice',icon:'⚄'},{id:'roulette',label:'Roulette',icon:'◎'},{id:'slots',label:'Slots',icon:'♜'}]

const money=(n:number)=>`${fmt(n)} VC`
function localLoad(): LocalStore { try { const x=JSON.parse(localStorage.getItem(LOCAL_KEY)||'null'); if(x?.players) return x } catch{} return {players:[],rounds:[],session:null,admin:false} }

export default function App(){
  const [local,setLocal]=useState<LocalStore>(localLoad)
  const [profile,setProfile]=useState<Profile|null>(null)
  const [mode,setMode]=useState<'login'|'register'|'admin'>('login')
  const [game,setGame]=useState<GameId>('keno')
  const [page,setPage]=useState<'games'|'admin'>('games')
  const [message,setMessage]=useState('')
  const [loading,setLoading]=useState(false)

  useEffect(()=>{ localStorage.setItem(LOCAL_KEY,JSON.stringify(local)) },[local])
  useEffect(()=>{
    if(!supabase) return
    supabase.auth.getSession().then(async ({data})=>{ if(data.session) await refreshProfile(data.session.user.id) })
    const {data:{subscription}}=supabase.auth.onAuthStateChange(async (_e,s)=>{ if(s) await refreshProfile(s.user.id); else setProfile(null) })
    return ()=>subscription.unsubscribe()
  },[])
  async function refreshProfile(uid:string){ if(!supabase) return; const {data}=await supabase.from('profiles').select('*').eq('id',uid).single(); if(data) setProfile({id:data.id,username:data.display_name||'Player',phone:data.phone||'',credits:Number(data.credits),active:true,joined:new Date(data.created_at).getTime(),role:data.role}) }
  const localPlayer=local.players.find(p=>p.id===local.session)||null
  const player=profile||localPlayer
  const isAdmin = Boolean(local.admin || profile?.role === 'admin')
  async function logout(){ if(supabase) await supabase.auth.signOut(); setProfile(null); setLocal(s=>({...s,session:null,admin:false})); setPage('games'); setMode('login') }
  async function debit(stake:number){ if(!player||player.credits<stake){setMessage('Not enough virtual credits.');return false}; if(supabase){ const {data,error}=await supabase.rpc('change_own_credits',{delta:-stake,reason:'Game stake'}); if(error){setMessage(error.message);return false}; setProfile(p=>p?{...p,credits:Number(data)}:p); return true } setLocal(s=>({...s,players:s.players.map(p=>p.id===player.id?{...p,credits:p.credits-stake}:p)})); return true }
  async function settle(stake:number,payout:number,label:string,gameId:GameId,metadata:Record<string,unknown>={}){ if(!player)return; if(supabase){ const {data,error}=await supabase.rpc('change_own_credits',{delta:payout,reason:`${gameId} payout`}); if(!error)setProfile(p=>p?{...p,credits:Number(data)}:p); await supabase.from('game_rounds').insert({player_id:player.id,game:gameId,stake,payout,label,metadata}); } else { setLocal(s=>({...s,players:s.players.map(p=>p.id===player.id?{...p,credits:p.credits+payout}:p),rounds:[{id:id(),at:Date.now(),game:gameId,stake,payout,label},...s.rounds]})) } }
  if(!player && !local.admin) return <Auth mode={mode} setMode={setMode} setLocal={setLocal} local={local} setProfile={setProfile} loading={loading} setLoading={setLoading}/>
  if(isAdmin) return <Admin local={local} setLocal={setLocal} logout={logout}/>
  return <div className="app"><Header player={player!} admin={false} logout={logout}/><main><GameNav game={game} setGame={setGame}/>{game==='keno'&&<Keno player={player!} debit={debit} settle={settle} message={message} setMessage={setMessage}/>} {game==='aviator'&&<Aviator player={player!} debit={debit} settle={settle} message={message} setMessage={setMessage}/>} {game==='dice'&&<Dice player={player!} debit={debit} settle={settle} message={message} setMessage={setMessage}/>} {game==='roulette'&&<Roulette player={player!} debit={debit} settle={settle} message={message} setMessage={setMessage}/>} {game==='slots'&&<Slots player={player!} debit={debit} settle={settle} message={message} setMessage={setMessage}/>}</main></div>
}

function Header({player,admin,logout}:{player:Player;admin:boolean;logout:()=>void}){return <header className="topbar"><div className="brand"><img src="/fastkeno.webp" alt="FAST KENO" className="fastkeno-logo"/><div className="site-name">ANAS <span>BET</span></div></div><div className="header-players"><span className="live-dot"></span><strong>128</strong><span>PLAYERS</span></div><div className="wallet"><span>{maskPhone(player.phone)||'Player'}</span><strong>{money(player.credits)}</strong></div>{admin&&<button className="admin-top">ADMIN</button>}<button className="logout" onClick={logout}>×</button></header>}

function maskPhone(phone:string){const raw=phone.replace(/\s/g,''); if(!raw) return ''; if(raw.length<=4) return `${raw.slice(0,1)}**${raw.slice(-1)}`; return `${raw.slice(0,2)}**${raw.slice(-2)}`}
function GameNav({game,setGame}:{game:GameId;setGame:(g:GameId)=>void}){return <nav className="game-nav">{games.map(g=><button key={g.id} className={game===g.id?'on':''} onClick={()=>setGame(g.id)}><span>{g.icon}</span>{g.label}</button>)}</nav>}

function Auth({mode,setMode,setLocal,local,setProfile,loading,setLoading}:{mode:'login'|'register'|'admin';setMode:(m:'login'|'register'|'admin')=>void;setLocal:Dispatch<SetStateAction<LocalStore>>;local:LocalStore;setProfile:(p:Profile|null)=>void;loading:boolean;setLoading:(v:boolean)=>void}){
 const [phone,setPhone]=useState(''),[password,setPassword]=useState(''),[email,setEmail]=useState(ADMIN_EMAIL),[error,setError]=useState('')
 async function submit(){setError('');setLoading(true);try{if(supabase){ if(mode==='admin'){const {data,error}=await supabase.auth.signInWithPassword({email,password}); if(error)throw error; const {data:p}=await supabase.from('profiles').select('*').eq('id',data.user.id).single(); if(p?.role!=='admin'){await supabase.auth.signOut();throw new Error('This account is not an admin.')} setProfile({id:p.id,username:p.display_name||'Admin',phone:p.phone||'',credits:Number(p.credits),active:true,joined:Date.now(),role:p.role}); return} if(mode==='register'){const {data,error}=await supabase.auth.signUp({phone:phone.replace(/\s/g,''),password,options:{data:{display_name:`Player ${phone.slice(-4)}`}}}); if(error)throw error; if(data.user&&!data.session)setError('Account created. If phone verification is enabled in Supabase, enter the SMS code before logging in.'); else if(data.user){const {data:p}=await supabase.from('profiles').select('*').eq('id',data.user.id).single(); if(p)setProfile({id:p.id,username:p.display_name||'Player',phone:p.phone||phone,credits:Number(p.credits),active:true,joined:Date.now(),role:p.role})} } else {const {data,error}=await supabase.auth.signInWithPassword({phone:phone.replace(/\s/g,''),password}); if(error)throw error; const {data:p}=await supabase.from('profiles').select('*').eq('id',data.user.id).single(); if(p)setProfile({id:p.id,username:p.display_name||'Player',phone:p.phone||phone,credits:Number(p.credits),active:true,joined:Date.now(),role:p.role})} } else { if(mode==='admin'){if(email.trim().toLowerCase()!==ADMIN_EMAIL||password!==ADMIN_PASSWORD)throw new Error('Admin email or password is incorrect.');setLocal(s=>({...s,admin:true}));return} const p=phone.replace(/\s/g,''); if(mode==='register'){if(!/^\+?[0-9]{7,15}$/.test(p))throw new Error('Enter a valid phone number.');if(password.length<6)throw new Error('Password must be at least 6 characters.');if(local.players.some(x=>x.phone===p))throw new Error('Phone already registered.');const a={id:id(),username:`Player ${p.slice(-4)}`,phone:p,credits:10000,active:true,joined:Date.now()};setLocal(s=>({...s,players:[...s.players,a],session:a.id}))}else{const a=local.players.find(x=>x.phone===p);if(!a)throw new Error('Player not found.');setLocal(s=>({...s,session:a.id}))}}}catch(e:any){setError(e.message||'Something went wrong')}finally{setLoading(false)}}
 return <div className="auth-page"><div className="auth-card"><div className="auth-logo"><span>◆</span> KENOPLAY</div>{mode!=='admin'?<><div className="auth-tabs"><button className={mode==='login'?'on':''} onClick={()=>setMode('login')}>LOGIN</button><button className={mode==='register'?'on':''} onClick={()=>setMode('register')}>REGISTER</button></div><h1>{mode==='register'?'Create your account':'Welcome back'}</h1><p>Phone number and password. Virtual credits only.</p><label>Phone number<input inputMode="tel" placeholder="+251911234567" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label></>:<><h1>Admin sign in</h1><p>Only approved admin accounts can access the control center.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label></>}{error&&<div className="error">{error}</div>}<button className="primary" disabled={loading} onClick={submit}>{loading?'PLEASE WAIT…':mode==='admin'?'ADMIN LOGIN':mode==='register'?'CREATE ACCOUNT':'LOGIN'}</button>{mode==='admin'?<button className="link" onClick={()=>setMode('login')}>Back to player login</button>:<button className="link" onClick={()=>setMode('admin')}>Admin sign in</button>} {!supabaseConfigured&&<small className="demo">Demo mode is active. Add Supabase keys to enable shared accounts.</small>}</div></div>
}

function Keno({player,debit,settle,message,setMessage}:{player:Player;debit:(n:number)=>Promise<boolean>;settle:(s:number,p:number,l:string,g:GameId,m?:Record<string,unknown>)=>Promise<void>;message:string;setMessage:(s:string)=>void}){
 const [picks,setPicks]=useState<number[]>([]),[drawn,setDrawn]=useState<number[]>([]),[bet,setBet]=useState(2),[left,setLeft]=useState(60),[drawing,setDrawing]=useState(false),[last,setLast]=useState<number[]>([]),[tab,setTab]=useState('game'),[round,setRound]=useState(0),[accepted,setAccepted]=useState(false)
 const otherTickets=useMemo(()=>Array.from({length:5},(_,i)=>({id:`ticket-${round}-${i}`,name:['y**e','m**n','a**r','h**d','s**a'][i],stake:[20,50,100,200,500][i],numbers:shuffle(nums()).slice(0,1+rnd(10)).sort((a,b)=>a-b)})),[round])
 const playerCount=128+((round*7)%24)
 useEffect(()=>{if(drawing)return;const t=setInterval(()=>setLeft(v=>v<=1?0:v-1),1000);return()=>clearInterval(t)},[drawing])
 useEffect(()=>{if(left!==0||drawing)return;startDraw()},[left])
 function toggle(n:number){if(drawing||accepted)return;setPicks(p=>p.includes(n)?p.filter(x=>x!==n):p.length<10?[...p,n]:p)}
 function quick(){if(!drawing&&!accepted)setPicks(shuffle(nums()).slice(0,Math.min(10,Math.max(1,1+rnd(10)))).sort((a,b)=>a-b))}
 async function placeBet(){if(picks.length<1||picks.length>10){setMessage('Choose 1 to 10 numbers.');return}if(await debit(bet)){setAccepted(true);setMessage(`BET ACCEPTED · ${picks.length} NUMBERS · WAIT FOR THE DRAW`)}}
 async function startDraw(){setDrawing(true);setAccepted(false);setDrawn([]);setLast([]);const pool=shuffle(nums()).slice(0,20);for(let i=0;i<pool.length;i++){await new Promise(r=>setTimeout(r,1000));setDrawn(d=>[...d,pool[i]]);setLast(d=>[...d,pool[i]])}const hits=picks.filter(n=>pool.includes(n)).length;const count=picks.length;const multiplierByCount:Record<number,number[]>={1:[0,2],2:[0,1,5],3:[0,0,2,12],4:[0,0,1,5,25],5:[0,0,0,2,10,50],6:[0,0,0,1,5,25,100],7:[0,0,0,1,3,12,60,250],8:[0,0,0,1,3,10,40,180,500],9:[0,0,0,0,2,7,25,100,350,1000],10:[0,0,0,1,2,5,12,30,80,200,500]};const payout=accepted?Math.floor(bet*(multiplierByCount[count]?.[hits]||0)):0;if(payout)await settle(bet,payout,`Keno ${hits}/${count}`,'keno',{draw:pool,hits,picks});setMessage(payout?`WIN ${money(payout)} · ${hits}/${count} MATCHES`:`${hits}/${count} MATCHES`);setPicks([]);setAccepted(false);setRound(x=>x+1);setLeft(60);setDrawing(false)}
 const countdown=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`
 return <div className="keno-wrap">
   <section className="keno-main">
     <div className="keno-head"><div className="mini-balance"><b>{money(player.credits)}</b><span>ID: {maskPhone(player.phone)||'PLAYER'}</span></div><div className="timer">{countdown}</div><div className="menu">☰</div></div>
     <div className="keno-result-box">
       <div className="result-title-row"><strong>{drawing?'DRAWING RESULTS':'NEXT DRAW'}</strong><span>{drawing?`${drawn.length} / 20`:'20 NUMBERS'}</span></div>
       {drawing || last.length>0 ? <div className="draw-result-grid">{(drawing?drawn:last).map((n,i)=><span className="draw-number" key={`${n}-${i}`}>{n}</span>)}{drawing&&Array.from({length:Math.max(0,20-drawn.length)}).map((_,i)=><span className="draw-number empty" key={`empty-${i}`}>—</span>)}</div> : <div className="next-draw-message"><div className="count-large">{countdown}</div><div>Choose 1 to 10 numbers from 1 to 80</div></div>}
     </div>
     <div className="keno-grid">{nums().map(n=><button key={n} className={picks.includes(n)?'pick':''} onClick={()=>toggle(n)}><b>{n}</b></button>)}</div>
     <div className="ticket-section">
       <div className="section-heading"><strong>YOUR SELECTED NUMBERS</strong><span>{picks.length}/10</span></div>
       <div className="ticket-box own-ticket">{picks.length? <div className="ticket-numbers">{picks.slice().sort((a,b)=>a-b).map(n=><span key={n} className={drawn.includes(n)?'hit':''}>{n}</span>)}</div>:<div className="empty-ticket">Select 1 to 10 numbers for your ticket</div>}</div>
       <div className="section-heading other-heading"><strong>OTHER PLAYERS · NUMBERS & STAKE</strong><span>{playerCount} PLAYERS LIVE</span></div>
       <div className="other-tickets">{otherTickets.map(ticket=><div className="ticket-box other-ticket" key={ticket.id}><div className="ticket-meta"><span>{ticket.name}</span><b>{money(ticket.stake)}</b></div><div className="ticket-numbers">{ticket.numbers.map(n=><span key={n}>{n}</span>)}</div></div>)}</div>
     </div>
     <div className="betbar"><button onClick={()=>setBet(v=>Math.max(1,v-1))}>−</button><strong>{bet}</strong><button onClick={()=>setBet(v=>v+1)}>+</button><button className="x2" onClick={()=>setBet(v=>Math.min(Math.max(1,player.credits),v*2))}>X2</button><button className="max" onClick={()=>setBet(Math.max(1,Math.floor(player.credits/10)))}>MAX</button><button className="bet-btn" disabled={drawing||picks.length<1||accepted} onClick={placeBet}>{accepted?'WAIT…':'BET'}</button></div>
     <div className="quick-row"><button onClick={quick} disabled={drawing||accepted}>QUICK PICK</button><span>{message}</span><button onClick={()=>{setPicks([]);setAccepted(false);setMessage('')}} disabled={drawing}>CLEAR</button></div>
     <div className="bottom-tabs">{['game','history','results','statistics'].map(x=><button className={tab===x?'on':''} onClick={()=>setTab(x)} key={x}>{x==='game'?'▶ GAME':x==='history'?'↶ HISTORY':x==='results'?'✓ RESULTS':'▥ STATISTICS'}</button>)}</div>
   </section>
   <aside className="keno-side"><Panel title="OTHER PLAYERS' SELECTIONS"><div className="popular">{[4,16,27,55,72,8].map(n=><div key={n}><span>{String(n).padStart(2,'0')}</span><i style={{width:`${Math.min(100,(2+rnd(15))*5)}%`}}/><small>{2+rnd(15)} picks</small></div>)}</div></Panel><Panel title="LATEST RESULTS"><div className="result-pills">{last.map((n,i)=><span key={`${n}-${i}`}>{n}</span>)}</div></Panel><Panel title="MY TICKET"><div className="result-pills">{picks.map(n=><span key={n}>{n}</span>)}</div></Panel></aside>
 </div>
}
function Panel({title,children}:{title:string;children:ReactNode}){return <div className="side-panel"><h3>{title}</h3>{children}</div>}

function Aviator({player,debit,settle,message,setMessage}:{player:Player;debit:(n:number)=>Promise<boolean>;settle:(s:number,p:number,l:string,g:GameId,m?:Record<string,unknown>)=>Promise<void>;message:string;setMessage:(s:string)=>void}){const [bet,setBet]=useState(100),[m,setM]=useState(1),[running,setRunning]=useState(false),[cashed,setCashed]=useState(false),[takeoff,setTakeoff]=useState(false),timer=useRef<number|null>(null);useEffect(()=>()=>{if(timer.current)clearInterval(timer.current)},[]);async function start(){if(running||!(await debit(bet)))return;setM(1);setCashed(false);setTakeoff(true);setMessage('Take-off…');setTimeout(()=>{setTakeoff(false);setRunning(true);timer.current=window.setInterval(()=>setM(v=>{const n=+(v+0.02+Math.random()*0.08).toFixed(2);if(n>=20){if(timer.current)clearInterval(timer.current);setRunning(false);setMessage('Plane flew away');return n}return n}),90)},900)}async function cash(){if(!running||cashed)return;const p=Math.floor(bet*m);setCashed(true);setRunning(false);if(timer.current)clearInterval(timer.current);await settle(bet,p,`Aviator ${m.toFixed(2)}x`,'aviator',{multiplier:m});setMessage(`Cashed out at ${m.toFixed(2)}x`)}return <div className="game-card aviator-card"><div className="sky"><div className="stars"/><div className="cloud c1"/><div className="cloud c2"/><div className={`flight ${takeoff?'takeoff':''}`} style={{'--flight':`${Math.min(100,(m-1)/19*100)}%`} as CSSProperties}><span>✈</span></div><div className="mult">{m.toFixed(2)}x</div><div className="status">{takeoff?'TAKE OFF':running?'FLYING':'READY'}</div></div><div className="controls-row"><label>BET<input type="number" min="1" value={bet} onChange={e=>setBet(Math.max(1,+e.target.value||1))}/></label><button className="primary" disabled={running||takeoff} onClick={start}>TAKE OFF</button><button className="cash" disabled={!running||cashed} onClick={cash}>CASH OUT</button></div><div className="message">{message}</div></div>}
function Dice({player,debit,settle,message,setMessage}:any){const [bet,setBet]=useState(100),[roll,setRoll]=useState(50),[rolling,setRolling]=useState(false);async function play(){if(rolling||!(await debit(bet)))return;setRolling(true);let i=0;const t=setInterval(()=>{setRoll(rnd(100)+1);if(++i>14){clearInterval(t);const r=rnd(100)+1;setRoll(r);const win=r<50;const p=win?bet*1.96:0;if(p)settle(bet,p,`Dice ${r}`,'dice',{roll:r});setMessage(win?`WIN ${money(p)}`:`Roll ${r} — no win`);setRolling(false)}},80)}return <div className="game-card center"><div className={`dice-orb ${rolling?'shake':''}`}>{roll}</div><h2>ROLL UNDER 50</h2><label>BET<input type="number" value={bet} onChange={e=>setBet(Math.max(1,+e.target.value||1))}/></label><button className="primary wide" onClick={play} disabled={rolling}>ROLL</button><div className="message">{message}</div></div>}
function Roulette({player,debit,settle,message,setMessage}:any){const [bet,setBet]=useState(100),[choice,setChoice]=useState('red'),[result,setResult]=useState(0),[spinning,setSpinning]=useState(false);async function spin(){if(spinning||!(await debit(bet)))return;setSpinning(true);let i=0;const t=setInterval(()=>{setResult(rnd(37));if(++i>18){clearInterval(t);const r=rnd(37);setResult(r);const color=r===0?'green':r%2?'red':'black';const p=color===choice?bet*(choice==='green'?35:2):0;if(p)settle(bet,p,`Roulette ${r}`,'roulette',{result:r,color});setMessage(p?`WIN ${money(p)}`:`${r} ${color}`);setSpinning(false)}},70)}return <div className="game-card center"><div className={`roulette-wheel ${spinning?'spin':''}`}><span>{result}</span></div><div className="choice-row">{['red','black','green'].map(c=><button className={choice===c?'selected':''} key={c} onClick={()=>setChoice(c)}>{c}</button>)}</div><label>BET<input type="number" value={bet} onChange={e=>setBet(Math.max(1,+e.target.value||1))}/></label><button className="primary wide" disabled={spinning} onClick={spin}>SPIN</button><div className="message">{message}</div></div>}
function Slots({player,debit,settle,message,setMessage}:any){const symbols=['🍒','🍋','🔔','⭐','7️⃣','💎'],[reels,setReels]=useState(['🍒','⭐','7️⃣']),[spinning,setSpinning]=useState(false),[bet,setBet]=useState(100);async function spin(){if(spinning||!(await debit(bet)))return;setSpinning(true);let i=0;const t=setInterval(()=>{setReels([symbols[rnd(6)],symbols[rnd(6)],symbols[rnd(6)]]);if(++i>12){clearInterval(t);const r=[symbols[rnd(6)],symbols[rnd(6)],symbols[rnd(6)]];setReels(r);const p=r.every(x=>x===r[0])?bet*20:(r[0]===r[1]||r[1]===r[2]||r[0]===r[2]?bet*3:0);if(p)settle(bet,p,`Slots ${r.join(' ')}`,'slots',{reels:r});setMessage(p?`WIN ${money(p)}`:'No match');setSpinning(false)}},75)}return <div className="game-card center"><div className={`slots ${spinning?'slot-spin':''}`}>{reels.map((r,i)=><div key={i}>{r}</div>)}</div><label>BET<input type="number" value={bet} onChange={e=>setBet(Math.max(1,+e.target.value||1))}/></label><button className="primary wide" disabled={spinning} onClick={spin}>SPIN</button><div className="message">{message}</div></div>}

function Admin({local,setLocal,logout}:{local:LocalStore;setLocal:Dispatch<SetStateAction<LocalStore>>;logout:()=>void}){
 const [remote,setRemote]=useState<Player[]>([]),[search,setSearch]=useState(''),[amount,setAmount]=useState(1000),[sel,setSel]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{ if(!supabase)return; supabase.from('profiles').select('id,phone,display_name,credits,created_at,role').order('created_at',{ascending:false}).then(({data})=>{ if(data)setRemote(data.filter(x=>x.role==='player').map(x=>({id:x.id,username:x.display_name||'Player',phone:x.phone||'',credits:Number(x.credits),active:true,joined:new Date(x.created_at).getTime()}))) }) },[])
 const players=supabase?remote:local.players
 const filtered=players.filter(p=>p.phone.includes(search.replace(/\s/g,'')))
 const target=players.find(p=>p.id===(sel||filtered[0]?.id))
 async function adjust(delta:number){ if(!target)return;setBusy(true);try{if(supabase){const {data,error}=await supabase.rpc('adjust_player_credits',{target:target.id,delta,note:delta>=0?'Admin credit addition':'Admin credit deduction'});if(error)throw error;setRemote(v=>v.map(p=>p.id===target.id?{...p,credits:Number(data)}:p))}else setLocal(s=>({...s,players:s.players.map(p=>p.id===target.id?{...p,credits:Math.max(0,p.credits+delta)}:p)}))}catch(e:any){alert(e.message||'Credit adjustment failed')}finally{setBusy(false)}}
 return <div className="admin-page"><header className="topbar"><div className="brand"><span className="brand-mark">◆</span><b>KENOPLAY ADMIN</b></div><button className="logout" onClick={logout}>×</button></header><main className="admin-wrap"><div className="admin-title"><div><small>ADMIN CONTROL CENTER</small><h1>Virtual Credit Control</h1><p>Search players by phone number and add or deduct virtual credits.</p></div><span className="connection">{supabase?'● SUPABASE CONNECTED':'● DEMO MODE'}</span></div><div className="admin-stats"><div><small>PLAYERS</small><b>{players.length}</b></div><div><small>TOTAL CREDITS</small><b>{money(players.reduce((a,p)=>a+p.credits,0))}</b></div></div><div className="admin-columns"><section className="side-panel"><h3>SEARCH PLAYER BY PHONE</h3><input placeholder="+251911234567" value={search} onChange={e=>setSearch(e.target.value)}/>{filtered.map(p=><button className={target?.id===p.id?'player-row selected':'player-row'} onClick={()=>setSel(p.id)} key={p.id}><span><b>{p.phone}</b><small>{p.username}</small></span><strong>{money(p.credits)}</strong></button>)}{!filtered.length&&<p className="muted">No player found.</p>}</section><section className="side-panel"><h3>ADD / DEDUCT VIRTUAL CREDITS</h3>{target?<><div className="selected-admin"><span>{target.phone}</span><strong>{money(target.credits)}</strong></div><input type="number" value={amount} onChange={e=>setAmount(Math.max(1,+e.target.value||1))}/><div className="adjust-buttons"><button disabled={busy} onClick={()=>adjust(amount)}>+ ADD CREDITS</button><button disabled={busy} onClick={()=>adjust(-amount)}>− DEDUCT</button></div></>:<p>Search for a player.</p>}</section></div></main></div>
}

